### ISSUE TITLE
OverlayStartApp.java line 113

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#163]
#### in com.fgl.thirdparty.overlay.OverlayStartApp.onAvailabilityResult

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b75f5476007d59fcdfde68d?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b75f5476007d59fcdfde68d?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
#0. Crashed: main
       at com.fgl.thirdparty.overlay.OverlayStartApp.onAvailabilityResult(OverlayStartApp.java:113)
       at com.fgl.thirdparty.overlay.OverlayStartApp.access$000(OverlayStartApp.java:21)
       at com.fgl.thirdparty.overlay.OverlayStartApp$1.onFailedToReceiveAd(OverlayStartApp.java:49)
       at com.startapp.android.publish.ads.banner.bannerstandard.BannerStandard.onFailedToReceiveBanner(StartAppSDK:481)
       at com.startapp.android.publish.ads.banner.bannerstandard.BannerStandard.onFailedToReceiveAd(StartAppSDK:549)
       at com.startapp.android.publish.adsCommon.adListeners.b$2.run(StartAppSDK:41)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5296)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

--

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
       at com.fgl.thirdparty.overlay.OverlayStartApp.onAvailabilityResult(OverlayStartApp.java:113)
       at com.fgl.thirdparty.overlay.OverlayStartApp.access$000(OverlayStartApp.java:21)
       at com.fgl.thirdparty.overlay.OverlayStartApp$1.onFailedToReceiveAd(OverlayStartApp.java:49)
       at com.startapp.android.publish.ads.banner.bannerstandard.BannerStandard.onFailedToReceiveBanner(StartAppSDK:481)
       at com.startapp.android.publish.ads.banner.bannerstandard.BannerStandard.onFailedToReceiveAd(StartAppSDK:549)
       at com.startapp.android.publish.adsCommon.adListeners.b$2.run(StartAppSDK:41)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5296)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
