### ISSUE TITLE
Webview

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#164]
#### in com.adcolony.sdk.ay.a

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7613e46007d59fcdffa32a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7613e46007d59fcdffa32a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
#0. Crashed: main
       at android.webkit.WebViewClassic.evaluateJavaScript(WebViewClassic.java:2674)
       at android.webkit.WebView.evaluateJavascript(WebView.java:905)
       at com.adcolony.sdk.ay.a(SourceFile:113)
       at com.adcolony.sdk.ay$a.onPageFinished(SourceFile:706)
       at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:324)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5001)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
       at dalvik.system.NativeStart.main(NativeStart.java)

--

Fatal Exception: java.lang.IllegalStateException: This API not supported on Android 4.3 and earlier
       at android.webkit.WebViewClassic.evaluateJavaScript(WebViewClassic.java:2674)
       at android.webkit.WebView.evaluateJavascript(WebView.java:905)
       at com.adcolony.sdk.ay.a(SourceFile:113)
       at com.adcolony.sdk.ay$a.onPageFinished(SourceFile:706)
       at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:324)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5001)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
       at dalvik.system.NativeStart.main(NativeStart.java)

#0. Crashed: main
       at android.webkit.WebViewClassic.evaluateJavaScript(WebViewClassic.java:2674)
       at android.webkit.WebView.evaluateJavascript(WebView.java:905)
       at com.adcolony.sdk.ay.a(SourceFile:113)
       at com.adcolony.sdk.ay$a.onPageFinished(SourceFile:706)
       at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:324)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5001)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by pavi2410** [comment]
It says AdColony,  not WebViewer
