### ISSUE TITLE
Leadbolt - Bug

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#17]
#### in com.apptracker.android.track.AppTracker.E

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b723f216007d59fcdb76fbb?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b723f216007d59fcdb76fbb?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
`Fatal Exception: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
       at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:225)
       at com.apptracker.android.track.AppTracker.E(l:293)
       at com.apptracker.android.track.AppTracker.startSession(l:137)
       at com.apptracker.android.track.AppTracker.startSession(l:216)
       at com.apptracker.android.track.AppTracker.startSession(l:109)
       at com.google.appinventor.components.runtime.LeadBolt.onInitialize(LeadBolt.java:163)
       at com.google.appinventor.components.runtime.Form$3.run(Form.java:858)`

**Comment by michael-winkler** [comment]
@conorshipp Can you please take a look to the leadbolt component? thanks

**Comment by NmdOfficial** [comment]
@conorshipp 
Form.java 858 (bugfix 1.0.5 branch)
`onInitializeListener.onInitialize();`

**Comment by michael-winkler** [comment]
Should be fixed now.
