### ISSUE TITLE
ColinTreeSlideshow.java line 126

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#24]
#### in cn.colintree.aix.ColinTreeSlideshow.ColinTreeSlideshow.TouchUp

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7275d56007d59fcdbac043?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7275d56007d59fcdbac043?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
ColinTreeSlideshow.java line 126
cn.colintree.aix.ColinTreeSlideshow.ColinTreeSlideshow.TouchUp

Extensions issue.

**Comment by Sander0542** [comment]
```
Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2122)
       at cn.colintree.aix.ColinTreeSlideshow.ColinTreeSlideshow.TouchUp(ColinTreeSlideshow.java:126)
       at cn.colintree.aix.ColinTreeSlideshow.ColinTreeSlideshow.onTouch(ColinTreeSlideshow.java:102)
       at android.view.View.dispatchTouchEvent(View.java:10072)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2779)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at com.google.appinventor.components.runtime.ScaledFrameLayout.dispatchTouchEvent(ScaledFrameLayout.java:79)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2785)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3063)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
       at android.view.View.dispatchPointerEvent(View.java:10312)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4949)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4808)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4315)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4368)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4334)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4480)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4342)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4537)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4315)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4368)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4334)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4342)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4315)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6844)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6818)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6761)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7016)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:6276)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```
