### ISSUE TITLE
Listview 

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#245]
#### in android.widget.TextView.sendOnTextChanged

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b78547f6007d59fcd291541?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b78547f6007d59fcd291541?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
#0. Crashed: main
       at com.google.appinventor.components.runtime.ListView$1.onTextChanged(ListView.java:107)
       at android.widget.TextView.sendOnTextChanged(TextView.java:10611)
       at android.widget.TextView.handleTextChanged(TextView.java:10715)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:14056)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:849)
       at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:618)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:396)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

--

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.Filter android.widget.ArrayAdapter.getFilter()' on a null object reference
       at com.google.appinventor.components.runtime.ListView$1.onTextChanged(ListView.java:107)
       at android.widget.TextView.sendOnTextChanged(TextView.java:10611)
       at android.widget.TextView.handleTextChanged(TextView.java:10715)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:14056)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:849)
       at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:618)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:396)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by michael-winkler** [comment]
already fixed
