### ISSUE TITLE
ActionBarContainer.java line 117

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#273]
#### in android.support.v7.widget.ActionBarContainer.setStackedBackground

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b790e2b6007d59fcd33a102?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b790e2b6007d59fcd33a102?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
#0. Crashed: main
       at android.support.v7.widget.ActionBarContainer.setStackedBackground(ActionBarContainer.java:117)
       at android.support.v7.app.WindowDecorActionBar.setStackedBackgroundDrawable(WindowDecorActionBar.java:487)
       at com.google.appinventor.components.runtime.Form.ChangeTabsColor(Form.java:2445)
       at com.google.appinventor.components.runtime.Form.addTabItemsOrIcons(Form.java:2388)
       at com.google.appinventor.components.runtime.Form.AddTitleBarTabs(Form.java:2373)
       at com.google.appinventor.components.runtime.Form$2.run(Form.java:481)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

--

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
       at android.support.v7.widget.ActionBarContainer.setStackedBackground(ActionBarContainer.java:117)
       at android.support.v7.app.WindowDecorActionBar.setStackedBackgroundDrawable(WindowDecorActionBar.java:487)
       at com.google.appinventor.components.runtime.Form.ChangeTabsColor(Form.java:2445)
       at com.google.appinventor.components.runtime.Form.addTabItemsOrIcons(Form.java:2388)
       at com.google.appinventor.components.runtime.Form.AddTitleBarTabs(Form.java:2373)
       at com.google.appinventor.components.runtime.Form$2.run(Form.java:481)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

#0. Crashed: main
       at android.support.v7.widget.ActionBarContainer.setStackedBackground(ActionBarContainer.java:117)
       at android.support.v7.app.WindowDecorActionBar.setStackedBackgroundDrawable(WindowDecorActionBar.java:487)
       at com.google.appinventor.components.runtime.Form.ChangeTabsColor(Form.java:2445)
       at com.google.appinventor.components.runtime.Form.addTabItemsOrIcons(Form.java:2388)
       at com.google.appinventor.components.runtime.Form.AddTitleBarTabs(Form.java:2373)
       at com.google.appinventor.components.runtime.Form$2.run(Form.java:481)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by michael-winkler** [comment]
This if fixed for next bug fix release
