### ISSUE TITLE
WhiteMobi

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#342]
#### in com.white.mobi.sdk.WMOfferWall$1.onItemClick

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7a86866007d59fcd4c698a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7a86866007d59fcd4c698a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
#0. Crashed: main
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
       at android.app.Activity.startActivityForResult(Activity.java:4261)
       at android.app.Activity.startActivityForResult(Activity.java:4220)
       at android.app.Activity.startActivity(Activity.java:4544)
       at android.app.Activity.startActivity(Activity.java:4512)
       at com.white.mobi.sdk.WMOfferWall$1.onItemClick(WMOfferWall.java:96)
       at android.widget.AdapterView.performItemClick(AdapterView.java:315)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1204)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3321)
       at android.widget.AbsListView$4.run(AbsListView.java:4382)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:208)
       at android.app.ActivityThread.main(ActivityThread.java:6267)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

--

Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://whitemobisdk.com/... }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
       at android.app.Activity.startActivityForResult(Activity.java:4261)
       at android.app.Activity.startActivityForResult(Activity.java:4220)
       at android.app.Activity.startActivity(Activity.java:4544)
       at android.app.Activity.startActivity(Activity.java:4512)
       at com.white.mobi.sdk.WMOfferWall$1.onItemClick(WMOfferWall.java:96)
       at android.widget.AdapterView.performItemClick(AdapterView.java:315)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1204)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3321)
       at android.widget.AbsListView$4.run(AbsListView.java:4382)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:208)
       at android.app.ActivityThread.main(ActivityThread.java:6267)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by conorshipp** [comment]
I'm not sure what the problem is here. I would assume it's user error since we created a sample app when testing the component and it worked fine.

**Comment by michael-winkler** [comment]
@conorshipp there are now more errors like that. Make sure you added all things to compiler
