### ISSUE TITLE
CustomMediaController bug

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#39]
#### in android.widget.MediaController.disableUnsupportedButtons

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72c2036007d59fcdc0e9f9?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72c2036007d59fcdc0e9f9?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by barreeeiroo** [comment]
Possible duplicated of #38

**Comment by michael-winkler** [comment]
`#0. Crashed: main
       at android.widget.MediaController.disableUnsupportedButtons(MediaController.java:327)
       at android.widget.MediaController.show(MediaController.java:366)
       at com.google.appinventor.components.runtime.util.CustomMediaController.show(CustomMediaController.java:50)
       at com.google.appinventor.components.runtime.util.CustomMediaController.onTouch(CustomMediaController.java:117)`

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.widget.MediaController$MediaPlayerControl.canPause()' on a null object reference
       at android.widget.MediaController.disableUnsupportedButtons(MediaController.java:327)
       at android.widget.MediaController.show(MediaController.java:366)
       at com.google.appinventor.components.runtime.util.CustomMediaController.show(CustomMediaController.java:50)
       at com.google.appinventor.components.runtime.util.CustomMediaController.onTouch(CustomMediaController.java:117)`

**Comment by michael-winkler** [comment]
I reported the issue to app inventor:
https://github.com/mit-cml/appinventor-sources/issues/1328
