### ISSUE TITLE
CommonStartApp.java line 76

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#457]
#### in com.fgl.thirdparty.common.CommonStartApp.onDataConsentStatusChange

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7c352f6007d59fcd6c5b93?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7c352f6007d59fcd6c5b93?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
#0. Crashed: main
       at com.fgl.thirdparty.common.CommonStartApp.onDataConsentStatusChange(CommonStartApp.java:76)
       at com.fgl.enhance.sdks.implementation.core.Sdk.setDataConsentStatus(Sdk.java:241)
       at com.fgl.enhance.Enhance.restoreDataConsentResults(Enhance.java:1530)
       at com.fgl.enhance.Enhance.onActivityResume(Enhance.java:399)
       at android.support.v4.app.SupportActivity.onResume(SupportActivity.java:71)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:446)
       at android.support.v7.app.AppCompatActivity.onResume(AppCompatActivity.java:68)
       at com.google.appinventor.components.runtime.Form.onResume(Form.java:676)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1291)
       at android.app.Activity.performResume(Activity.java:6793)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3527)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3596)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2831)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6339)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

--

Fatal Exception: java.lang.NoSuchMethodError: No static method setUserConsent(Landroid/content/Context;Ljava/lang/String;JZ)V in class Lcom/startapp/android/publish/adsCommon/StartAppSDK; or its super classes (declaration of 'com.startapp.android.publish.adsCommon.StartAppSDK' appears in /mnt/expand/d6ab678f-5558-494f-a3b4-26a3f8115ab5/app/com.assistirfilmesgratis.filmesonline-1/base.apk:classes6.dex)
       at com.fgl.thirdparty.common.CommonStartApp.onDataConsentStatusChange(CommonStartApp.java:76)
       at com.fgl.enhance.sdks.implementation.core.Sdk.setDataConsentStatus(Sdk.java:241)
       at com.fgl.enhance.Enhance.restoreDataConsentResults(Enhance.java:1530)
       at com.fgl.enhance.Enhance.onActivityResume(Enhance.java:399)
       at android.support.v4.app.SupportActivity.onResume(SupportActivity.java:71)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:446)
       at android.support.v7.app.AppCompatActivity.onResume(AppCompatActivity.java:68)
       at com.google.appinventor.components.runtime.Form.onResume(Form.java:676)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1291)
       at android.app.Activity.performResume(Activity.java:6793)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3527)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3596)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2831)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6339)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

#0. Crashed: main
       at com.fgl.thirdparty.common.CommonStartApp.onDataConsentStatusChange(CommonStartApp.java:76)
       at com.fgl.enhance.sdks.implementation.core.Sdk.setDataConsentStatus(Sdk.java:241)
       at com.fgl.enhance.Enhance.restoreDataConsentResults(Enhance.java:1530)
       at com.fgl.enhance.Enhance.onActivityResume(Enhance.java:399)
       at android.support.v4.app.SupportActivity.onResume(SupportActivity.java:71)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:446)
       at android.support.v7.app.AppCompatActivity.onResume(AppCompatActivity.java:68)
       at com.google.appinventor.components.runtime.Form.onResume(Form.java:676)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1291)
       at android.app.Activity.performResume(Activity.java:6793)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3527)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3596)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2831)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6339)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
