### ISSUE TITLE
FusiontablesControl bug

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#47]
#### in android.view.WindowManagerGlobal.findViewLocked

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72dc3e6007d59fcdc34b76?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b72dc3e6007d59fcdc34b76?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
Fusiontables component bug

`#0. Crashed: main
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:451)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:377)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:140)
       at android.app.Dialog.dismissDialog(Dialog.java:701)
       at android.app.Dialog.dismiss(Dialog.java:684)
       at com.google.appinventor.components.runtime.FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:982)
       at com.google.appinventor.components.runtime.FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:794)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

--

Fatal Exception: java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{3ecab11 V.E...... R......D 0,0-668,232} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:451)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:377)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:140)
       at android.app.Dialog.dismissDialog(Dialog.java:701)
       at android.app.Dialog.dismiss(Dialog.java:684)
       at com.google.appinventor.components.runtime.FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:982)
       at com.google.appinventor.components.runtime.FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:794)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

#0. Crashed: main
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:451)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:377)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:140)
       at android.app.Dialog.dismissDialog(Dialog.java:701)
       at android.app.Dialog.dismiss(Dialog.java:684)
       at com.google.appinventor.components.runtime.FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:982)
       at com.google.appinventor.components.runtime.FusiontablesControl$QueryProcessorV2.onPostExecute(FusiontablesControl.java:794)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by michael-winkler** [comment]
Reported to App Inventor:
https://github.com/mit-cml/appinventor-sources/issues/1329
