### ISSUE TITLE
HorizontalScrollHandler.java line 123

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#62]
#### in cn.colintree.aix.ScrollArrangementHandlers.HorizontalScrollHandler$2.onMove

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7358ad6007d59fcdcd4b49?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7358ad6007d59fcdcd4b49?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
`Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2218)
       at cn.colintree.aix.ScrollArrangementHandlers.HorizontalScrollHandler$2.onMove(HorizontalScrollHandler.java:123)
       at cn.colintree.aix.ScrollArrangementHandlers.HorizontalScrollHandler$2.onTouch(HorizontalScrollHandler.java:105)
       at android.view.View.dispatchTouchEvent(View.java:11730)`
