### ISSUE TITLE
TinyWebDB

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#796]
#### in org.apache.http.impl.client.DefaultRequestDirector.determineRoute

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b87ee706007d59fcd3db1ae?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b87ee706007d59fcd3db1ae?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
#0. Crashed: Thread-16904
       at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:607)
       at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:303)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:588)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:686)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:660)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:649)
       at com.google.appinventor.components.runtime.util.WebServiceUtil.postCommand(WebServiceUtil.java:164)
       at com.google.appinventor.components.runtime.TinyWebDB.postStoreValue(TinyWebDB.java:210)
       at com.google.appinventor.components.runtime.TinyWebDB.access$000(TinyWebDB.java:70)
       at com.google.appinventor.components.runtime.TinyWebDB$1.run(TinyWebDB.java:155)
       at java.lang.Thread.run(Thread.java:818)

--

Fatal Exception: java.lang.IllegalStateException: Target host must not be null, or set in parameters. scheme=null, host=null, path=meprowallet.atwebpages.com/storeavalue
       at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:607)
       at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:303)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:588)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:686)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:660)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:649)
       at com.google.appinventor.components.runtime.util.WebServiceUtil.postCommand(WebServiceUtil.java:164)
       at com.google.appinventor.components.runtime.TinyWebDB.postStoreValue(TinyWebDB.java:210)
       at com.google.appinventor.components.runtime.TinyWebDB.access$000(TinyWebDB.java:70)
       at com.google.appinventor.components.runtime.TinyWebDB$1.run(TinyWebDB.java:155)
       at java.lang.Thread.run(Thread.java:818)
