### ISSUE TITLE
SQLite line 89

### ISSUE THREAD

**Issue by KodularCreator** [Makeroid/BugsTracker#87]
#### in android.widget.Toast$TN.<init>

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7421db6007d59fcddaa630?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/makeroid4/android/apps/io.makeroid.application/issues/5b7421db6007d59fcddaa630?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by michael-winkler** [comment]
`at com.google.appinventor.components.runtime.SQLite$ExecuteSQL.doInBackground(SQLite.java:89)
       at com.google.appinventor.components.runtime.SQLite$ExecuteSQL.doInBackground(SQLite.java:83)`
